### ISSUE TITLE
Test api with webserver

### ISSUE THREAD

**Issue by Tvax** [Tvax/vuejs-gravatar#1]
Set the api to the webserver and try displaying an avatar

**Comment by Sainormagoden** [comment]
le projet vue doit etre utiliser avec c9... je sais pas comment ça marche

**Comment by Sainormagoden** [comment]
mais en reprenant le cours de levron c'est fais rapidement la connection api et d'afficher l'image

**Comment by Tvax** [comment]
Comment ca avec c9?
Tu fais juste un npm install et c'est bon nan?

**Comment by Tvax** [comment]
C'est que je peux pas tester en local a cause de leur windows de mort a l'iut

**Comment by Sainormagoden** [comment]
d'acc, non il me renvoie quand même sur c9, mais je vais me débrouiller. On se voit vite fais cette aprem et au pire je bosserais pour la prochaine fois ^^'

**Comment by Tvax** [comment]
Ha ouais je sais, sur le cours de levron t'as un truc pour l'utiliser avec C9. Faut que tu l'enleves, c'est dans la package.json je crois.
